app.service('StationService', function() {
  this._stations = [
    {
      stationName: "ALTUF'YEVO",
      xPosition: 480,
      yPosition: 110,
      stationId: 0,
      stationDescription: "Esta es una descripción en ruso.",
      lineId: 1,
      factionId: 0
    }, {
      stationName: "BIBIREVO",
      xPosition: 506,
      yPosition: 135.5,
      stationId: 1,
      stationDescription: "",
      lineId: 0,
      factionId: 0
    }, {
      stationName: "OTRADNOE",
      xPosition: 506,
      yPosition: 168,
      stationId: 2,
      stationDescription: "",
      lineId: 0,
      factionId: 0
    }, {
      stationName: "VLADYKINO",
      xPosition: 506,
      yPosition: 201,
      stationId: 3,
      stationDescription: "",
      lineId: 0,
      factionId: 0
    }, {
      stationName: "PETROVSKO-RAZUMOVSKAYA",
      xPosition: 482,
      yPosition: 224,
      stationId: 4,
      stationDescription: "",
      lineId: 0,
      factionId: 0
    }, {
      stationName: "TIMIRYAZEVSKAYA",
      xPosition: 481.5,
      yPosition: 255.5,
      stationId: 5,
      stationDescription: "",
      lineId: 0,
      factionId: 0
    }, {
      stationName: "DMITROVSKAYA",
      xPosition: 482,
      yPosition: 285.5,
      stationId: 6,
      stationDescription: "",
      lineId: 0,
      factionId: 0
    }, {
      stationName: "SAVELOVSKAYA",
      xPosition: 482,
      yPosition: 314,
      stationId: 7,
      stationDescription: "",
      lineId: 0,
      factionId: 0
    }, {
      stationName: "MENDELEEVSKAYA",
      xPosition: 482.5,
      yPosition: 346,
      stationId: 8,
      stationDescription: "",
      lineId: 0,
      factionId: 0
    }, {
      stationName: "NOVOSLOBODSKAYA",
      xPosition: 504,
      yPosition: 368,
      stationId: 9,
      stationDescription: "",
      lineId: 0,
      factionId: 0
    }, {
      stationName: "TSVETNOY BULVAR",
      xPosition: 578,
      yPosition: 446,
      stationId: 10,
      stationDescription: "",
      lineId: 0,
      factionId: 0
    }, {
      stationName: "CHEKHOVSKAYA",
      xPosition: 500,
      yPosition: 524,
      stationId: 11,
      stationDescription: "",
      lineId: 0,
      factionId: 0
    }, {
      stationName: "ALEKSANDROVSKIY SAD",
      xPosition: 501,
      yPosition: 624,
      stationId: 12,
      stationDescription: "",
      lineId: 0,
      factionId: 0
    }, {
      stationName: "BOROVITSKAYA",
      xPosition: 502,
      yPosition: 667,
      stationId: 13,
      stationDescription: "",
      lineId: 0,
      factionId: 0
    }, {
      stationName: "POLYANKA",
      xPosition: 515,
      yPosition: 761,
      stationId: 14,
      stationDescription: "",
      lineId: 0,
      factionId: 0
    }, {
      stationName: "DOBRYNINSKAYA",
      xPosition: 608,
      yPosition: 854,
      stationId: 15,
      stationDescription: "",
      lineId: 0,
      factionId: 0
    }, {
      stationName: "BULVAR DMITRIYA DONSKOGO",
      xPosition: 609,
      yPosition: 1212,
      stationId: 16,
      stationDescription: "",
      lineId: 0,
      factionId: 0
    }, {
      stationName: "ANNINO",
      xPosition: 610,
      yPosition: 1184,
      stationId: 17,
      stationDescription: "",
      lineId: 0,
      factionId: 0
    }, {
      stationName: "UL. AKADEMIKA YANGELYA",
      xPosition: 609,
      yPosition: 1159,
      stationId: 18,
      stationDescription: "",
      lineId: 0,
      factionId: 0
    }, {
      stationName: "PRAZHSKAYA",
      xPosition: 609,
      yPosition: 1131,
      stationId: 19,
      stationDescription: "",
      lineId: 0,
      factionId: 0
    }, {
      stationName: "YUZHNAYA",
      xPosition: 610,
      yPosition: 1104,
      stationId: 20,
      stationDescription: "",
      lineId: 0,
      factionId: 0
    }, {
      stationName: "CHERTANOVSKAYA",
      xPosition: 575,
      yPosition: 1072,
      stationId: 21,
      stationDescription: "",
      lineId: 0,
      factionId: 0
    }, {
      stationName: "SEVASTOPOLSKAYA",
      xPosition: 574,
      yPosition: 1042,
      stationId: 22,
      stationDescription: "",
      lineId: 0,
      factionId: 0
    }, {
      stationName: "NAKHIMOVSKIY PROSPEKT",
      xPosition: 575,
      yPosition: 1014,
      stationId: 23,
      stationDescription: "",
      lineId: 0,
      factionId: 0
    }, {
      stationName: "NAGORNAYA",
      xPosition: 574,
      yPosition: 986,
      stationId: 24,
      stationDescription: "",
      lineId: 0,
      factionId: 0
    }, {
      stationName: "NAGATINSKAYA",
      xPosition: 607,
      yPosition: 955,
      stationId: 25,
      stationDescription: "",
      lineId: 0,
      factionId: 0
    }, {
      stationName: "TUL'SKAYA",
      xPosition: 608,
      yPosition: 921,
      stationId: 26,
      stationDescription: "",
      lineId: 0,
      factionId: 0
    }, {
      stationName: "SERPUKHOVSKAYA",
      xPosition: 608,
      yPosition: 884,
      stationId: 27,
      stationDescription: "",
      lineId: 0,
      factionId: 0
    }, {
      stationName: "MEDVEDKOVO",
      xPosition: 754.5,
      yPosition: 125,
      stationId: 28,
      stationDescription: "",
      lineId: 0,
      factionId: 0
    }, {
      stationName: "BABUSHKINSKAYA",
      xPosition: 755,
      yPosition: 165,
      stationId: 29,
      stationDescription: "",
      lineId: 0,
      factionId: 0
    }, {
      stationName: "SVIBLOVO",
      xPosition: 730,
      yPosition: 190,
      stationId: 30,
      stationDescription: "",
      lineId: 0,
      factionId: 0
    }, {
      stationName: "BOTANICHESKIY SAD",
      xPosition: 705,
      yPosition: 217,
      stationId: 31,
      stationDescription: "",
      lineId: 0,
      factionId: 0
    }, {
      stationName: "VDNKH (EXHIBITION)",
      xPosition: 704.5,
      yPosition: 255.5,
      stationId: 32,
      stationDescription: "",
      lineId: 0,
      factionId: 0
    }, {
      stationName: "ALEKSEEVSKAYA",
      xPosition: 705,
      yPosition: 293,
      stationId: 33,
      stationDescription: "",
      lineId: 0,
      factionId: 0
    }, {
      stationName: "RIZHSKAYA",
      xPosition: 705,
      yPosition: 333,
      stationId: 34,
      stationDescription: "",
      lineId: 0,
      factionId: 0
    }, {
      stationName: "PROSPEKT MIRA",
      xPosition: 704,
      yPosition: 368,
      stationId: 35,
      stationDescription: "",
      lineId: 0,
      factionId: 0
    }, {
      stationName: "PROSPEKT MIRA",
      xPosition: 683,
      yPosition: 390,
      stationId: 36,
      stationDescription: "",
      lineId: 0,
      factionId: 0
    }, {
      stationName: "SUKHAREVSKAYA",
      xPosition: 682,
      yPosition: 423,
      stationId: 37,
      stationDescription: "",
      lineId: 0,
      factionId: 0
    }, {
      stationName: "TURGENEVSKAYA",
      xPosition: 683,
      yPosition: 515,
      stationId: 38,
      stationDescription: "",
      lineId: 0,
      factionId: 0
    }, {
      stationName: "KITAY-GOROD",
      xPosition: 684,
      yPosition: 662,
      stationId: 39,
      stationDescription: "",
      lineId: 0,
      factionId: 0
    }, {
      stationName: "TRETYAKOVSKAYA",
      xPosition: 593,
      yPosition: 752,
      stationId: 40,
      stationDescription: "",
      lineId: 0,
      factionId: 0
    }, {
      stationName: "OKTYABR'SKAYA",
      xPosition: 521,
      yPosition: 823,
      stationId: 41,
      stationDescription: "",
      lineId: 0,
      factionId: 0
    }, {
      stationName: "OKTYABR'SKAYA",
      xPosition: 499,
      yPosition: 845,
      stationId: 42,
      stationDescription: "",
      lineId: 0,
      factionId: 0
    }, {
      stationName: "BITZEVSKY PARK",
      xPosition: 411,
      yPosition: 1150,
      stationId: 43,
      stationDescription: "",
      lineId: 0,
      factionId: 0
    }, {
      stationName: "YASENEVO",
      xPosition: 388,
      yPosition: 1126,
      stationId: 44,
      stationDescription: "",
      lineId: 0,
      factionId: 0
    }, {
      stationName: "TEPLIY STAN",
      xPosition: 363,
      yPosition: 1102,
      stationId: 45,
      stationDescription: "",
      lineId: 0,
      factionId: 0
    }, {
      stationName: "KON'KOVO",
      xPosition: 363,
      yPosition: 1069,
      stationId: 46,
      stationDescription: "",
      lineId: 0,
      factionId: 0
    }, {
      stationName: "BELYAEVO",
      xPosition: 364,
      yPosition: 1039,
      stationId: 47,
      stationDescription: "",
      lineId: 0,
      factionId: 0
    }, {
      stationName: "KALUZHSKAYA",
      xPosition: 386,
      yPosition: 1015,
      stationId: 48,
      stationDescription: "",
      lineId: 0,
      factionId: 0
    }, {
      stationName: "NOVYE CHEREMUSHKI",
      xPosition: 409,
      yPosition: 993,
      stationId: 49,
      stationDescription: "",
      lineId: 0,
      factionId: 0
    }, {
      stationName: "PROFSOYUZNAYA",
      xPosition: 433,
      yPosition: 970,
      stationId: 50,
      stationDescription: "",
      lineId: 0,
      factionId: 0
    }, {
      stationName: "AKADEMICHESKAYA",
      xPosition: 455,
      yPosition: 948,
      stationId: 51,
      stationDescription: "",
      lineId: 0,
      factionId: 0
    }, {
      stationName: "LENINSKIY PROSPEKT",
      xPosition: 477,
      yPosition: 924,
      stationId: 52,
      stationDescription: "",
      lineId: 0,
      factionId: 0
    }, {
      stationName: "SHABOLOVSKAYA",
      xPosition: 499,
      yPosition: 902,
      stationId: 53,
      stationDescription: "",
      lineId: 0,
      factionId: 0
    }, {
      stationName: "ULITSA PODBEL'SKOGO",
      xPosition: 872,
      yPosition: 253,
      stationId: 54,
      stationDescription: "",
      lineId: 0,
      factionId: 0
    }, {
      stationName: "CHERKIZOVSKAYA",
      xPosition: 872.5,
      yPosition: 295,
      stationId: 55,
      stationDescription: "",
      lineId: 0,
      factionId: 0
    }, {
      stationName: "PREOBRAZHENSKAYA PLOSCHAD'",
      xPosition: 846,
      yPosition: 323,
      stationId: 56,
      stationDescription: "",
      lineId: 0,
      factionId: 0
    }, {
      stationName: "SOKOL'NIKI",
      xPosition: 818,
      yPosition: 349,
      stationId: 57,
      stationDescription: "",
      lineId: 0,
      factionId: 0
    }, {
      stationName: "KRANSNOSEL'SKAYA",
      xPosition: 791,
      yPosition: 377,
      stationId: 58,
      stationDescription: "",
      lineId: 0,
      factionId: 0
    }, {
      stationName: "KOMSOLMOL'SKAYA",
      xPosition: 762,
      yPosition: 409,
      stationId: 59,
      stationDescription: "",
      lineId: 0,
      factionId: 0
    }, {
      stationName: "KOMSOLMOL'SKAYA",
      xPosition: 741,
      yPosition: 430,
      stationId: 60,
      stationDescription: "",
      lineId: 0,
      factionId: 0
    }, {
      stationName: "KRASNYE VOROTA",
      xPosition: 712,
      yPosition: 457,
      stationId: 61,
      stationDescription: "",
      lineId: 0,
      factionId: 0
    }, {
      stationName: "CHISTYE PRUDY",
      xPosition: 683,
      yPosition: 483,
      stationId: 62,
      stationDescription: "",
      lineId: 0,
      factionId: 0
    }, {
      stationName: "TEATRAL'NAYA",
      xPosition: 567,
      yPosition: 603,
      stationId: 63,
      stationDescription: "",
      lineId: 0,
      factionId: 0
    }, {
      stationName: "KROPOTKINSKAYA",
      xPosition: 442,
      yPosition: 729,
      stationId: 64,
      stationDescription: "",
      lineId: 0,
      factionId: 0
    }, {
      stationName: "YUGO-ZAPADNAYA",
      xPosition: 187,
      yPosition: 987,
      stationId: 65,
      stationDescription: "",
      lineId: 0,
      factionId: 0
    }, {
      stationName: "PROSPEKT VERNADSKOGO",
      xPosition: 217,
      yPosition: 956,
      stationId: 66,
      stationDescription: "",
      lineId: 0,
      factionId: 0
    }, {
      stationName: "UNIVERSITET",
      xPosition: 247,
      yPosition: 926,
      stationId: 67,
      stationDescription: "",
      lineId: 0,
      factionId: 0
    }, {
      stationName: "VOROB'EVY GORY",
      xPosition: 279,
      yPosition: 892,
      stationId: 68,
      stationDescription: "",
      lineId: 0,
      factionId: 0
    }, {
      stationName: "SPORTIVNAYA",
      xPosition: 323,
      yPosition: 849,
      stationId: 69,
      stationDescription: "",
      lineId: 0,
      factionId: 0
    }, {
      stationName: "FRUNZENSKAYA",
      xPosition: 358,
      yPosition: 813,
      stationId: 70,
      stationDescription: "",
      lineId: 0,
      factionId: 0
    }, {
      stationName: "PARK KUL'TURY",
      xPosition: 391,
      yPosition: 778,
      stationId: 71,
      stationDescription: "",
      lineId: 0,
      factionId: 0
    }, {
      stationName: "SCHELKOVSKAYA",
      xPosition: 986,
      yPosition: 427,
      stationId: 72,
      stationDescription: "",
      lineId: 0,
      factionId: 0
    }, {
      stationName: "PERVOMAYSKAYA",
      xPosition: 987,
      yPosition: 463,
      stationId: 73,
      stationDescription: "",
      lineId: 0,
      factionId: 0
    }, {
      stationName: "IZMAYLOVSKAYA",
      xPosition: 987,
      yPosition: 502,
      stationId: 74,
      stationDescription: "",
      lineId: 0,
      factionId: 0
    }, {
      stationName: "PARTIZANSKAYA",
      xPosition: 961,
      yPosition: 528,
      stationId: 75,
      stationDescription: "",
      lineId: 0,
      factionId: 0
    }, {
      stationName: "SEMYONOVSKAYA",
      xPosition: 935,
      yPosition: 555,
      stationId: 76,
      stationDescription: "",
      lineId: 0,
      factionId: 0
    }, {
      stationName: "ELEKTROZAVODSKAYA",
      xPosition: 910,
      yPosition: 581,
      stationId: 77,
      stationDescription: "",
      lineId: 0,
      factionId: 0
    }, {
      stationName: "BAUMANSKAYA",
      xPosition: 885,
      yPosition: 607,
      stationId: 78,
      stationDescription: "",
      lineId: 0,
      factionId: 0
    }, {
      stationName: "KURSKAYA",
      xPosition: 846,
      yPosition: 643,
      stationId: 79,
      stationDescription: "",
      lineId: 0,
      factionId: 0
    }, {
      stationName: "CHKALOVSKAYA",
      xPosition: 831,
      yPosition: 669,
      stationId: 80,
      stationDescription: "",
      lineId: 0,
      factionId: 0
    }, {
      stationName: "KURSKAYA",
      xPosition: 816,
      yPosition: 644,
      stationId: 81,
      stationDescription: "",
      lineId: 0,
      factionId: 0
    }, {
      stationName: "PLOSCHAD' REVOLUTSII",
      xPosition: 612,
      yPosition: 644,
      stationId: 82,
      stationDescription: "",
      lineId: 0,
      factionId: 0
    }, {
      stationName: "BIBLIOTEKA IM. LENINA",
      xPosition: 523,
      yPosition: 645,
      stationId: 83,
      stationDescription: "",
      lineId: 0,
      factionId: 0
    }, {
      stationName: "ARBATSKAYA",
      xPosition: 479,
      yPosition: 645,
      stationId: 84,
      stationDescription: "",
      lineId: 0,
      factionId: 0
    }, {
      stationName: "SMOLENSKAYA",
      xPosition: 418,
      yPosition: 646,
      stationId: 85,
      stationDescription: "",
      lineId: 0,
      factionId: 0
    }, {
      stationName: "PARK POBEDY",
      xPosition: 180,
      yPosition: 737,
      stationId: 86,
      stationDescription: "",
      lineId: 0,
      factionId: 0
    }, {
      stationName: "KIEVSKAYA",
      xPosition: 327,
      yPosition: 741,
      stationId: 87,
      stationDescription: "",
      lineId: 0,
      factionId: 0
    }, {
      stationName: "KIEVSKAYA",
      xPosition: 325,
      yPosition: 698,
      stationId: 88,
      stationDescription: "",
      lineId: 0,
      factionId: 0
    }, {
      stationName: "KIEVSKAYA",
      xPosition: 349,
      yPosition: 720,
      stationId: 89,
      stationDescription: "",
      lineId: 0,
      factionId: 0
    }, {
      stationName: "NOVOGIREEVO",
      xPosition: 1010,
      yPosition: 657,
      stationId: 90,
      stationDescription: "",
      lineId: 0,
      factionId: 0
    }, {
      stationName: "PEROVO",
      xPosition: 983,
      yPosition: 685,
      stationId: 91,
      stationDescription: "",
      lineId: 0,
      factionId: 0
    }, {
      stationName: "SCHOSSE ENTUZIASTOV",
      xPosition: 956,
      yPosition: 712,
      stationId: 92,
      stationDescription: "",
      lineId: 0,
      factionId: 0
    }, {
      stationName: "AVIAMOTORNAYA",
      xPosition: 928,
      yPosition: 739,
      stationId: 93,
      stationDescription: "",
      lineId: 0,
      factionId: 0
    }, {
      stationName: "PLOSHAD' IL'YICHA",
      xPosition: 867,
      yPosition: 765,
      stationId: 94,
      stationDescription: "",
      lineId: 0,
      factionId: 0
    }, {
      stationName: "MARKSISTSKAYA",
      xPosition: 801,
      yPosition: 766,
      stationId: 95,
      stationDescription: "",
      lineId: 0,
      factionId: 0
    }, {
      stationName: "NOVOKUZNETSKAYA",
      xPosition: 619,
      yPosition: 767,
      stationId: 96,
      stationDescription: "",
      lineId: 0,
      factionId: 0
    }, {
      stationName: "VYHINO",
      xPosition: 1032,
      yPosition: 896,
      stationId: 97,
      stationDescription: "",
      lineId: 0,
      factionId: 0
    }, {
      stationName: "RYAZANSKY PROSPEKT",
      xPosition: 997,
      yPosition: 898,
      stationId: 98,
      stationDescription: "",
      lineId: 0,
      factionId: 0
    }, {
      stationName: "KUZMINKY",
      xPosition: 961,
      yPosition: 896,
      stationId: 99,
      stationDescription: "",
      lineId: 0,
      factionId: 0
    }, {
      stationName: "TEKSTIL'SCHIKI",
      xPosition: 941,
      yPosition: 876,
      stationId: 100,
      stationDescription: "",
      lineId: 0,
      factionId: 0
    }, {
      stationName: "VOLGOGRADSKY PROSPEKT",
      xPosition: 910,
      yPosition: 845,
      stationId: 101,
      stationDescription: "",
      lineId: 0,
      factionId: 0
    }, {
      stationName: "PROLETARSKAYA",
      xPosition: 867,
      yPosition: 803,
      stationId: 102,
      stationDescription: "",
      lineId: 0,
      factionId: 0
    }, {
      stationName: "TAGANSKAYA",
      xPosition: 801,
      yPosition: 737,
      stationId: 103,
      stationDescription: "",
      lineId: 0,
      factionId: 0
    }, {
      stationName: "TAGANSKAYA",
      xPosition: 775,
      yPosition: 751,
      stationId: 104,
      stationDescription: "",
      lineId: 0,
      factionId: 0
    }, {
      stationName: "KITAY-GOROD",
      xPosition: 726,
      yPosition: 664,
      stationId: 105,
      stationDescription: "",
      lineId: 0,
      factionId: 0
    }, {
      stationName: "KUZNETSKY MOST",
      xPosition: 638,
      yPosition: 574,
      stationId: 106,
      stationDescription: "",
      lineId: 0,
      factionId: 0
    }, {
      stationName: "LUBYANKA",
      xPosition: 617,
      yPosition: 553,
      stationId: 107,
      stationDescription: "",
      lineId: 0,
      factionId: 0
    }, {
      stationName: "TVERSKAYA",
      xPosition: 515,
      yPosition: 550,
      stationId: 108,
      stationDescription: "",
      lineId: 0,
      factionId: 0
    }, {
      stationName: "PUSHKINSKAYA",
      xPosition: 486,
      yPosition: 550,
      stationId: 109,
      stationDescription: "",
      lineId: 0,
      factionId: 0
    }, {
      stationName: "BARRIKADNAYA",
      xPosition: 357,
      yPosition: 553,
      stationId: 110,
      stationDescription: "",
      lineId: 0,
      factionId: 0
    }, {
      stationName: "PLANERNAYA",
      xPosition: 199,
      yPosition: 303,
      stationId: 111,
      stationDescription: "",
      lineId: 0,
      factionId: 0
    }, {
      stationName: "SHODNENSKAYA",
      xPosition: 200,
      yPosition: 345,
      stationId: 112,
      stationDescription: "",
      lineId: 0,
      factionId: 0
    }, {
      stationName: "TUSHINSKAYA",
      xPosition: 200,
      yPosition: 387,
      stationId: 113,
      stationDescription: "",
      lineId: 0,
      factionId: 0
    }, {
      stationName: "SCHUKINSKAYA",
      xPosition: 200,
      yPosition: 429,
      stationId: 114,
      stationDescription: "",
      lineId: 0,
      factionId: 0
    }, {
      stationName: "OKTYABR'SKOE POLE",
      xPosition: 225,
      yPosition: 454,
      stationId: 115,
      stationDescription: "",
      lineId: 0,
      factionId: 0
    }, {
      stationName: "POLEZHAEVSKAYA",
      xPosition: 250,
      yPosition: 478,
      stationId: 116,
      stationDescription: "",
      lineId: 0,
      factionId: 0
    }, {
      stationName: "BEGOVAYA",
      xPosition: 275,
      yPosition: 503,
      stationId: 117,
      stationDescription: "",
      lineId: 0,
      factionId: 0
    }, {
      stationName: "ULITSA 1905 GODA",
      xPosition: 300,
      yPosition: 528,
      stationId: 118,
      stationDescription: "",
      lineId: 0,
      factionId: 0
    }, {
      stationName: "KRASNOPRESNENSKAYA",
      xPosition: 326,
      yPosition: 552,
      stationId: 119,
      stationDescription: "",
      lineId: 0,
      factionId: 0
    }, {
      stationName: "MAR'YINO",
      xPosition: 907,
      yPosition: 1042,
      stationId: 120,
      stationDescription: "",
      lineId: 0,
      factionId: 0
    }, {
      stationName: "BRATISLAVSKAYA",
      xPosition: 907,
      yPosition: 1015,
      stationId: 121,
      stationDescription: "",
      lineId: 0,
      factionId: 0
    }, {
      stationName: "LYUBLINO",
      xPosition: 907,
      yPosition: 991,
      stationId: 122,
      stationDescription: "",
      lineId: 0,
      factionId: 0
    }, {
      stationName: "VOLZHSKAYA",
      xPosition: 907,
      yPosition: 964,
      stationId: 123,
      stationDescription: "",
      lineId: 0,
      factionId: 0
    }, {
      stationName: "PECHATNIKI",
      xPosition: 888,
      yPosition: 945,
      stationId: 124,
      stationDescription: "",
      lineId: 0,
      factionId: 0
    }, {
      stationName: "KOZHUHOVSKAYA",
      xPosition: 866,
      yPosition: 925,
      stationId: 125,
      stationDescription: "",
      lineId: 0,
      factionId: 0
    }, {
      stationName: "DUBROVKA",
      xPosition: 866,
      yPosition: 887,
      stationId: 126,
      stationDescription: "",
      lineId: 0,
      factionId: 0
    }, {
      stationName: "KREST'YANSKAYA ZASTAVA",
      xPosition: 866,
      yPosition: 834,
      stationId: 127,
      stationDescription: "",
      lineId: 0,
      factionId: 0
    }, {
      stationName: "RIMSKAYA",
      xPosition: 867,
      yPosition: 734,
      stationId: 128,
      stationDescription: "",
      lineId: 0,
      factionId: 0
    }, {
      stationName: "SRETENSKY BULVAR",
      xPosition: 648,
      yPosition: 488,
      stationId: 129,
      stationDescription: "",
      lineId: 0,
      factionId: 0
    }, {
      stationName: "TRUBNAYA",
      xPosition: 608,
      yPosition: 446,
      stationId: 130,
      stationDescription: "",
      lineId: 0,
      factionId: 0
    }, {
      stationName: "DOSTOYEVSKAYA",
      xPosition: 607,
      yPosition: 333,
      stationId: 131,
      stationDescription: "",
      lineId: 0,
      factionId: 0
    }, {
      stationName: "MAR'YINA ROSCHA",
      xPosition: 607,
      yPosition: 297,
      stationId: 132,
      stationDescription: "",
      lineId: 0,
      factionId: 0
    }, {
      stationName: "RECHNOY VOKZAL",
      xPosition: 302,
      yPosition: 208,
      stationId: 133,
      stationDescription: "",
      lineId: 0,
      factionId: 0
    }, {
      stationName: "VODNY STADION",
      xPosition: 302,
      yPosition: 248,
      stationId: 134,
      stationDescription: "",
      lineId: 0,
      factionId: 0
    }, {
      stationName: "VOIKOVSKAYA",
      xPosition: 302,
      yPosition: 288,
      stationId: 135,
      stationDescription: "",
      lineId: 0,
      factionId: 0
    }, {
      stationName: "SOKOL",
      xPosition: 302,
      yPosition: 332,
      stationId: 136,
      stationDescription: "",
      lineId: 0,
      factionId: 0
    }, {
      stationName: "AEROPORT",
      xPosition: 324,
      yPosition: 355,
      stationId: 137,
      stationDescription: "",
      lineId: 0,
      factionId: 0
    }, {
      stationName: "DINAMO",
      xPosition: 349,
      yPosition: 380,
      stationId: 138,
      stationDescription: "",
      lineId: 0,
      factionId: 0
    }, {
      stationName: "BELORUSSKAYA",
      xPosition: 376,
      yPosition: 409,
      stationId: 139,
      stationDescription: "",
      lineId: 0,
      factionId: 0
    }, {
      stationName: "BELORUSSKAYA",
      xPosition: 398,
      yPosition: 430,
      stationId: 140,
      stationDescription: "",
      lineId: 0,
      factionId: 0
    }, {
      stationName: "MAYAKOVSKAYA",
      xPosition: 447,
      yPosition: 480,
      stationId: 141,
      stationDescription: "",
      lineId: 0,
      factionId: 0
    }, {
      stationName: "OKHOTNY RYAD",
      xPosition: 569,
      yPosition: 602,
      stationId: 142,
      stationDescription: "",
      lineId: 0,
      factionId: 0
    }, {
      stationName: "NOVOKUZNETSKAYA",
      xPosition: 592,
      yPosition: 783,
      stationId: 143,
      stationDescription: "",
      lineId: 0,
      factionId: 0
    }, {
      stationName: "KRASNOGVARDEYSKAYA",
      xPosition: 847,
      yPosition: 1181,
      stationId: 144,
      stationDescription: "",
      lineId: 0,
      factionId: 0
    }, {
      stationName: "DOMODEDOVSKAYA",
      xPosition: 823,
      yPosition: 1155,
      stationId: 145,
      stationDescription: "",
      lineId: 0,
      factionId: 0
    }, {
      stationName: "OREHOVO",
      xPosition: 799,
      yPosition: 1131,
      stationId: 146,
      stationDescription: "",
      lineId: 0,
      factionId: 0
    }, {
      stationName: "TSARITSYNO",
      xPosition: 773,
      yPosition: 1105,
      stationId: 147,
      stationDescription: "",
      lineId: 0,
      factionId: 0
    }, {
      stationName: "KANTEMIROVSKAYA",
      xPosition: 748,
      yPosition: 1080,
      stationId: 148,
      stationDescription: "",
      lineId: 0,
      factionId: 0
    }, {
      stationName: "KASHIRSKAYA",
      xPosition: 749,
      yPosition: 1043,
      stationId: 149,
      stationDescription: "",
      lineId: 0,
      factionId: 0
    }, {
      stationName: "KOLOMENSKAYA",
      xPosition: 749,
      yPosition: 1008,
      stationId: 150,
      stationDescription: "",
      lineId: 0,
      factionId: 0
    }, {
      stationName: "AVTOZAVODSKAYA",
      xPosition: 749,
      yPosition: 936,
      stationId: 151,
      stationDescription: "",
      lineId: 0,
      factionId: 0
    }, {
      stationName: "PAVELETSKAYA",
      xPosition: 676,
      yPosition: 861,
      stationId: 152,
      stationDescription: "",
      lineId: 0,
      factionId: 0
    }, {
      stationName: "PAVELETSKAYA",
      xPosition: 655,
      yPosition: 841,
      stationId: 153,
      stationDescription: "",
      lineId: 0,
      factionId: 0
    }, {
      stationName: "KRYLATSKOE",
      xPosition: 99,
      yPosition: 514,
      stationId: 154,
      stationDescription: "",
      lineId: 0,
      factionId: 0
    }, {
      stationName: "MOLODEZHNAYA",
      xPosition: 99,
      yPosition: 559,
      stationId: 155,
      stationDescription: "",
      lineId: 0,
      factionId: 0
    }, {
      stationName: "KUNTSEVSKAYA",
      xPosition: 99,
      yPosition: 606,
      stationId: 156,
      stationDescription: "",
      lineId: 0,
      factionId: 0
    }, {
      stationName: "PIONERSKAYA",
      xPosition: 123,
      yPosition: 632,
      stationId: 157,
      stationDescription: "",
      lineId: 0,
      factionId: 0
    }, {
      stationName: "FILEVSKIY PARK",
      xPosition: 145,
      yPosition: 655,
      stationId: 158,
      stationDescription: "",
      lineId: 0,
      factionId: 0
    }, {
      stationName: "BAGRATIONOVSKAYA",
      xPosition: 167,
      yPosition: 676,
      stationId: 159,
      stationDescription: "",
      lineId: 0,
      factionId: 0
    }, {
      stationName: "FILI",
      xPosition: 189,
      yPosition: 699,
      stationId: 160,
      stationDescription: "",
      lineId: 0,
      factionId: 0
    }, {
      stationName: "KUTUZOVSKAYA",
      xPosition: 210,
      yPosition: 719,
      stationId: 161,
      stationDescription: "",
      lineId: 0,
      factionId: 0
    }, {
      stationName: "STUDENCHESKAYA",
      xPosition: 257,
      yPosition: 762,
      stationId: 162,
      stationDescription: "",
      lineId: 0,
      factionId: 0
    }, {
      stationName: "SMOLENSKAYA",
      xPosition: 398,
      yPosition: 626,
      stationId: 163,
      stationDescription: "",
      lineId: 0,
      factionId: 0
    }, {
      stationName: "ARBATSKAYA",
      xPosition: 460,
      yPosition: 625,
      stationId: 164,
      stationDescription: "",
      lineId: 0,
      factionId: 0
    }, {
      stationName: "BELORUSSKAYA",
      xPosition: 398,
      yPosition: 430,
      stationId: 165,
      stationDescription: "",
      lineId: 0,
      factionId: 0
    }, {
      stationName: "PAVELETSKAYA",
      xPosition: 655,
      yPosition: 841,
      stationId: 166,
      stationDescription: "",
      lineId: 0,
      factionId: 0
    }, {
      stationName: "KAHOVSKAYA",
      xPosition: 605,
      yPosition: 1043,
      stationId: 167,
      stationDescription: "",
      lineId: 0,
      factionId: 0
    }, {
      stationName: "VARSHAVSKAYA",
      xPosition: 664,
      yPosition: 1043,
      stationId: 168,
      stationDescription: "",
      lineId: 0,
      factionId: 0
    }, {
      stationName: "KASHIRSKAYA",
      xPosition: 721,
      yPosition: 1043,
      stationId: 169,
      stationDescription: "",
      lineId: 0,
      factionId: 0
    }
  ];

  this.getList = function() {
    return this._stations;
  };

  this.getById = function(stationId) {
    return this._stations.findByProperty('stationId', stationId);
  };
});
